INSERT INTO restaurante(restaurante_id, nombre, descripcion, categoria_restaurante_id, villa_id)
VALUES ('001', 'Antigua Hacienda', 'Platillos tradicionales de la comida mexicana, tortillas hechas a mano, deliciosas bebidas, postres y un exquisito sazón.','06','2')
	   , ('002', 'Café D´ París', 'Bebidas calientes o frías, crepas dulces o saladas, pastelería y delicioso pan','02','4')
       , ('003', 'Capone\'s  ', '¡Deliciosa pizza y pasta!','05','7')
       , ('004', 'Centro de relleno boulevard Justice League', 'No hagas filas! Rellena tu vaso souvenir o cubeta palomera.','05','1')
       , ('005', 'DC VIllains Grill', 'Deliciosas hamburguesas, crujientes tiras de pollo y refrescantes malteadas.','03','1')
       , ('006', 'Estación Coca Cola Francés ', 'Bebidas de la familia Coca Cola, Agua Ciel, Palomitas, Nachos, Icee y mucho más.','01','4')
       , ('007', 'Estación Coca Cola Hollywood', 'Bebidas de la familia Coca Cola, Agua Ciel, Palomitas, Nachos, Icee y mucho más.','01','1')
       , ('008', 'Estación Fanta', 'Bebidas de la familia Coca Cola, Agua Ciel, Palomitas, Nachos, Icee y mucho más.','01','2')
       , ('009', 'Funnel Cake  ', 'Funnel Cake, bebidas, churros rellenos y más','07','2')
       , ('010', 'Go Fresh Mexicano', 'Variedad de frutas de temporada, agua de sabor y más.','04','2')
       , ('011', 'Go Fresh Suizo', 'Variedad de frutas de temporada, agua de sabor y más.','04','2')
       , ('012', 'Grill Hollywood', '¡Deliciosos Hot Dogs a la parrilla!','03','1')
       , ('013', 'Hot Dog Grill Boulevard Justice League', 'Los mejores hot dogs de Metropolis: texas chilli dog, pulled pork y tocino.','03','1')
       , ('014', 'Johnny Rockets Hollywood', 'Hamburguesas, papas fritas, aros de cebolla y malteadas.','03','1')
       , ('015', 'Johnny Rockets Mexicano', 'Hamburguesas, papas fritas, aros de cebolla y malteadas.','03','2')
       , ('016', 'La Barrica Hollywood', 'Refrescante cerveza Corona.','01','1')
       , ('017', 'La Crepería', 'Bebidas calientes o frías, crepas dulces o saladas.','02','10')
       , ('018', 'Papa Kahuna', 'Papas al horno rellenas de jamón, tocino, o champicrema, nachos, icee y más.','03','2')
       , ('019', 'Parrilla Vaquera', 'Hamburguesas, papas fritas, y ensalada de vegetales.','03','6')
       , ('020', 'Saloon Corona', 'Pueblo Vaquero', 'Comida del viejo Oeste: Cortes de carne, alitas, ensaladas, postres y más.','03','6')
       , ('021', 'Six Pizza Hollywood', 'Variedad de pizzas, elige tu favorita.','05','1')
       , ('022', 'Six Pizza Vaquero', 'Variedad de pizzas, elige tu favorita.','05','6')
       , ('023', 'Super Snacks', 'Bebidas de la familia Coca Cola, Agua Ciel, Palomitas, Nachos, Icee y mucho más.','01','5')
       , ('024', 'Super Villanos Grill', 'Hamburguesas, papas fritas, y ensalada de vegetales.','03','2')
       , ('025', 'Taquería Jacaranda', 'Tacos al pastor, de suadero, bistec, gringas y más.','06','2')
       , ('026', 'Volcano Wings', 'Deliciosas alitas, boneless y refrescante cerveza de barril.','03','9')
       , ('027', 'Beachside Grill', 'Disfruta con el calor de una cerveza sola o preparada tu elijes! También prueba nuestros nuevos calimochos o si quieres algo más tropical te va a encantar nuestra piña colada! También para los peques se refresquen pídeles una canica seguro les encantará!','01','11')
       , ('028', 'Fábrica de Pollo', 'Prueba nuestros tradicionales pollos rostizados acompañados de una ensalada','06','11')
       , ('029', 'H2O Snacks', 'Rellena tu cubeta palomera o vaso souvenir','01','11')
       , ('030', 'Johnny Rockets', 'Hamburguesas, papas fritas, aros de cebolla y malteadas.','03','11')
       , ('031', 'La Antigua Hacienda', 'Aquí encontrarás una gran variedad de gastronomía mexicana','06','11')
       , ('032', 'La Hamaca Snacks', 'Rellena tu cubeta palomera o tu vaso souvenir', '01','11')
       , ('033', 'Sharks Snacks', 'Refréscate con una botella de agua o un refresco o alguno de los sabores de nuestras bebidas congeladas carbonatadas, ¿antojo de una papas? Aquí podrás encontrarlas para compartirlas', '01','11')
       , ('034', 'Six Pizza', 'Aquí podrás encontrar tu pizza favorita seguramente pepperoni, hawaiana disfrútalas al máximo. Complementa tu experiencia con una pasta a la boloñesa. No, olvides que también contamos con ensaladas para acompañar tus alimentos.', '05','11');
       
