INSERT INTO servicio (parque_id
                            , nombre
                            , descripcion
                            , precio
                            , deposito_inicial
) VALUES
      -- ¿Mex?
    (1,'ATM','¿Necesitas dinero en efectivo? ¡No es ningún problema! \n Nuestros Cajeros Automáticos están convenientemente ubicados por todo el parque',0,85.35)
    , (1,'CENTRO PARA EL CUIDADO DE BEBÉS','Disponemos de un centro para que las mamás puedan atender a sus bebés lactantes y cambiar los pañales. Éste se encuentra dentro del Centro de Información, en el Pueblo Suizo. También, en todos los sanitarios de damas y en los de caballeros, encontrarás espacio para cambiar a tu bebé.',0,0)
    , (1,'PRIMEROS AUXILIOS','Estación de Primeros Auxilios. Está al lado de Huracán, en Pueblo Vaquero.',0,0)
    , (1,'LOCKERS','Para tu comodidad el parque cuenta con el servicio de renta de lockers, ubicados en : * Entrada del Parque * Medusa * The Dark Knight Coaster * Go Karts * The Joker * Superman * Justice League Battle.\n“El número de lockers es limitado.” Te recomendamos una cangurera simple para disfrutar de los Juegos Mecánicos.',150,150)
    , (1,'ESTACIONAMIENTO','Recuerda que el parque y nuestro estacionamiento tienen un aforo máximo. Por tal motivo, en caso de ser necesario el parque cerrará sus puertas por cuestiones de seguridad (aplica para socios pase anual y/o boletos comprados en línea)',200,0)
    , (1,'CARRIOLAS','¿Necesitas un descanso por cargar a tus niños mucho tiempo en el parque? Las carriolas se rentan por orden de llegada. Para tu conveniencia, rentamos carriolas sencillas y dobles en el Pueblo Mexicano.',120,120)
    , (1,'SILLAS DE RUEDAS Y ASISTENCIA PARA VISITANTES CON DISCAPACIDAD','Nos esforzamos para garantizar que Six Flags México sea divertido y accesible para todos. Muchos de nuestros visitantes con discapacidad disfrutan en el parque todos los días. Podrás ingresar con sillas de ruedas y carros eléctricos. Son bienvenidos los visitantes con discapacidad y queremos hacer que su visita sea confortable e inolvidable. Los visitantes con discapacidad que requieran la ayuda de un Asistente de Cuidado Personal (ACP) con el fin de disfrutar la igualdad de acceso al parque, pueden solicitar a Six Flags México un pase sin costo para su ACP. Después de comprar sus boletos, por favor dirígete a Atención al Visitante y pregunta a los miembros del equipo por una solicitud de acceso para Asistente de Cuidado Personal. Este acceso NO es para disfrutar del parque, sino para realizar los cuidados que la persona con discapacidad requiera.',600,150)
    , (1,'CUBETA PALOMERA Y VASO REFIL','Los productos de cubeta palomera y vaso refill, deberán ser del año presente. Es decir, del año calendario que se está cursando, siempre y cuando sea el producto que Six Flags México o Hurricane Harbor Oaxtepec hayan autorizado. Cubetas y Vasos de años anteriores no podrán ingresar al parque.',50,400)
    , (1,'CUIDADO DE MASCOTAS','Sabemos que amas a tus mascotas y nosotros también amamos a los animales, pero no pueden venir a Six Flags México contigo. El servicio de Cuidador de Mascotas no está disponible. Las mascotas no pueden dejarse, ni atarse a un vehículo desatendido en el estacionamiento.',0,0)
       -- ¿U.S.A?
    , (2,'ATMs','Need Cash? No problem! ATMs are conveniently located throughout the park. Here’s where you can find them: -Main Gate -Hospitality -SUPERMAN Store -Candy Storm -Sangerfest Halle -Crackaxle Canyon -Crow’s Nest Ferris Wheel -Tornado - White Water Canyon', 0,0)
    , (2,'FIRST AID','If you get a cut or scrape or need a little TLC, head over to our Health Services Station located next to Sangerfest Halle in Spassburg. Guests may store medications here during their visit. Groups with medical release forms should check in at this station. A second Health Services Station is also available in White Water Bay.\nAll injuries must be reported to first aid prior to leaving the park.', 0,0)
    , (2,'KID SWAP','Parents of children under 54″ can notify a ride operator they’d like to participate in a Kid Swap. This allows one parent to wait in a designated area with the child while the other rides. Then they swap places! Feel free to stop by Guest Relations for more information.', 0,0)
    , (2,'LOCKERS','If you’d prefer not to lug your belongings around with you all day, we offer all-day storage locker rental in the Main Gate Area next to the turnstiles and by BATMAN™ The Ride, and can be purchased with credit cards.', 150,150)
    , (2,'LOST AND FOUND','Lose something? Don’t worry—it may have already been found! Lost and Found is located behind Guest Relations in Six Flags Plaza. Items will be retrieved from ride areas when the park closes and kept at Lost and Found for seven days.',0,0)
    , (2,'INFORMATION DESK AND CUSTOMER SERVICE','You have additional questions or just want to know what events are taking place today, go to the information desk located at the main entrance. A member of our team will be happy to assist you.\n You will also find several services:\n – Information about our accessibility program – Official size measurement with bracelets – Found items – Lost children',0,0)
    , (2,'RESTROOMS, DRINKING FOUNTAINS, TELEPHONES','You’ll find restrooms and drinking fountains conveniently located throughout the park.',0,0)
    , (2,'STROLLERS','Need a break from carrying your youngsters around the park? Strollers are rented on a first-come, first-serve basis. For your convenience, single, double and vehicle strollers are available to rent, next to the lockers after the Entry Plaza.', 16, 12)
    , (2,'THE FLASH PASS','Virtually reserve your place in the queue and save time with the Flash Pass! ',0,0)
    , (2,'WHEELCHAIRS & ASSISTANCE FOR GUESTS WITH DISABILITIES','We strive to make sure that Six Flags is fun and accessible for everyone. Lots of guests with disabilities enjoy the park every day. For your convenience, wheelchair rentals are also available next to the lockers after the Entry Plaza. The deposit is required for wheelchair and ECV rentals. Because there are a limited number of wheelchairs and ECVs for rent, we suggest you bring your own and/or come early to ensure availability.', 16,16)
    , (2,'CARD PAYMENTS ONLY','Six Flags Over Texas only accepts card at all in-park locations including restaurants, retail stores, games, ticket windows, and all parking toll booths. No card? No problem! Visit one of our kiosks in the park to take advantage of the cash-to-a-card program, which allows you to convert your cash to a prepaid debit card. Not only can you use this card throughout your visit, feel free to use leftover funds anywhere in the U.S. where VISA is accepted. Switching to card payments means there’s more options! You can pay for purchases using a VISA, Mastercard, American Express, Discover, or debit card', 0,0)
;