INSERT INTO atraccion (
	villa_id,
    tipo_atraccion_id,
    nivel_emocion_id,
    fabricante_id,
    nombre,
    descripcion,
    estado,
    consideracion,
    duracion,
    anio_introducido,
    costo,
    capacidad,
    velocidad_max_km,
    elevacion_m,
    largo_m
)
VALUES
	(1,2,3,1,'Aquaman Splashdown','En días calurosos, mojarse es una sensación agradable, pero no porque el agua se encuentre más fría que el aire, sino porque conduce mejor el calor de tu cuerpo hacia el exterior, lo que sentimos refrescante. Lo anterior lo has sentido en muchos lados, como, por ejemplo, al lavarte las manos. Si las sacudes de un lado para otro cuando están mojadas sentirás muy fresco; diferente a sacudirlas sin nada de líquido sobre ellas. Pero ten cuidado, no debes permanecer mucho tiempo mojado porque te puedes resfriar. Recomendación: Una vez que te empapes con todos tus amigos por culpa del Aquaman ponte un rato a los rayos del Sol para que el calor evapore el agua de tu ropa. ¿Y cómo se forma esta cascada de lluvia artificial? La responsable es la velocidad del carrito-lancha del Aquaman, ya que al tocar el agua provoca un empujón sobre el líquido y algunas moléculas, al chocar con otras, son desviadas hacia arriba. La cantidad de agua que forma la lluvia en cascada depende de la energía de la lancha, que a su vez depende de la masa de la misma y de la masa de los tripulantes. Es decir, entre más tripulantes tenga, más agua será lanzada hacia arriba. ¡De este juego saldrás empapado!','Funcionando','0.90 m acompañados de un adulto. A partir de 1.20 m podrán ingresar solos.','00:02:30',1976,0,20,70,18.2,250)
    , (1,1,1,2,'Batman The Ride','La estructura de Batman descansa sobre dados de cimentación hasta de 2 m de profundidad. Dicha profundidad se calcula a partir de un estudio de las propiedades del suelo del lugar donde se va a instalar una montaña rusa. Cálculos por supuesto, que requirió Bruce Wayne. Prepárate a subir a 32 metros y rodar libremente hasta velocidades de 80 kilómetros por hora colgado del tren de Batman The Ride.En el camino, el juego te hará girar y te pondrá de cabeza. Sentirás que flotas y luego que el estómago se te va a los pies. ¡Pero no corres peligro! La fuerza centrífuga te mantendrá en tu sitio. La fuerza centrífuga te empuja hacia fuera de una curva cuando el vehículo va rápido o la curva es muy cerrada. La fuerza centrífuga se usa también para entrenar pilotos y astronautas. El piloto se sienta en una silla sujeta al extremo de un brazo giratorio. La fuerza centrífuga simula las fuertes aceleraciones que se sienten en una nave espacial. ','Funcionando','1.30 m','00:02:30',2000,0,40,80,33.3,689)
    , (1,1,3,2,'Boomerang','El boomerang es un invento de los aborígenes australianos. Sirve para cazar y en su vuelo va dando vueltas. Un boomerang bien lanzado regresa a la mano del cazador. El Boomerang de Six Flags México hará lo mismo contigo. Boomerang  es la única montaña rusa de este parque que no empieza subiendo una cuesta para acumular energía potencial. En vez de eso, Boomerang acelera hasta alcanzar la energía cinética necesaria para hacer los giros y subir hasta su altura máxima de 37 metros. Luego hace el recorrido en reversa.','Funcionando','1.25 m','00:02:00',1988,0,28,75,35.5,285)
    , (1,1,1,3,'Crazanity','El péndulo que rompe récords está en Six Flags México. CraZanity es la atracción en forma de péndulo más alto del mundo, alcanzando asombrosos 50 metros sobre el aire. En esta nueva aventura, te sentarás en el exterior de un disco circular gigante que se balancea hacia adelante y hacia atrás mientras gira de lado a lado y se balanceará más y más, alcanzando alturas que desafían la gravedad de hasta 17 pisos en el aire, antes de sentir la ingravidez en tu estómago a 120 kilómetros por hora. ¡Mientras se balancea, al mismo tiempo girará en sentido contrario a las manecillas del reloj.','Funcionando','1.32 m','00:02:30',2020,0,40,120,53,130)
    , (1,1,1,4,'Supergirl Sky Flight','Volando a una sorprendente altura de 74 metros, Supergirl Sky Flight ofrece a sus visitantes estremecedoras vistas panorámicas, mientras giran observando el parque y la ciudad bajo ellos durante casi 2 minutos.','Funcionando','1.12 m acompañados de un adulto. A partir de 1.22 m podrán ingresar solos.','00:02:00',2015,0,32,64,74,100)
    , (2,1,1,5,'Superman El Último Escape','En este recorrido podrás conocer el Diario “El Planeta”, donde si tienes suerte podrás ver trabajar a Clark Kent o Lois Lane en sus oficinas, para después emprender un emocionante viaje al cielo. Las montañas rusas modernas son máquinas de precisión y alta tecnología. La estructura está calculada para aguantar fuerzas tremendas. El sistema electrónico de control, con sus sensores y computadoras, regula el funcionamiento de motores y frenos para garantizar tu seguridad. Diseñar y construir roller coasters es un trabajo complicado, pero claro que para el superhéroe más poderoso, no es ningún problema: se trata de diseñar una experiencia extrema, y al mismo tiempo completamente segura. En Superman El Último Escape altura de la caída más alta es de 65 metros, equivalente a la altura de un edificio de 20 pisos. Atrévete a sentir la adrenalina de nuestra roller coaster más alta.','Funcionando','1.30 m','00:02:30',2005,0,36,120,65,1700)
    , (3,2,2,6,'The Dark Knight Coaster','Basada en el enemigo principal del Caballero de la Noche, esta roller coaster te convertirá en un ciudadano ejemplar de Ciudad Gótica. Atrapado en el centro de la cuidad te verás envuelto en las artimañas que te tiene preparado el Joker y su banda de secuaces. Te llevará mediante un ferry a través de pasillos demenciales de giros, vueltas, subidas imprevistas e imágenes caóticas para vivir una experiencia inmersa en la oscuridad, donde tu única esperanza será ser salvado por El Caballero de la Noche.','Funcionando','1.05 m acompañados de un adulto. A partir de 1.20 m podrán ingresar solos.','00:02:00',2009,0,40,70,32,370)
    , (4,2,1,7,'The Joker','The Joker es la oportunidad que esperabas de conjuntar varios juegos en uno solo, porque pocos juegos del mundo te harán experimentar una diversidad de movimientos. El recorrido comienza en una Funhouse rediseñada por el archienemigo de Batman. Después experimentarás subidas, bajadas, medias vueltas, giros y aumentos de velocidad y un freno inesperado.  Ningún otro juego conjuga estos cambios bruscos de velocidad con giros que te provocarán un ataque de risa, tal como The Joker lo tenía planeado.','Funcionando','1.05 m acompañados de un adulto. A partir de 1.20 m podrán ingresar solos','00:01:30',2013,0,32,50,16.2,411)
    , (1,1,1,8,'Wonder Woman Coaster','Esta roller coaster presenta una temática basada en la icónica superheroína de DC, Wonder Woman. Su diseño exclusivo ofrece a los visitantes una experiencia única. Los pasajeros van suspendidos en ambos lados de las vías e irán girando durante el recorrido. Es la única atracción en Latinoamérica con el revolucionario sistema 4D Free Fly Coaster.','Funcionando','1.22 m','00:02:00',2018,0,8,61,34,650)
    , (5,3,3,9,'ACME Trucking Company','Se parte de este divertido viaje en enormes camiones que ayudarán a Wile E. Coyote a tratar de capturar al Correcaminos.','Funcionando','0.90 m acompañados de un adulto. A partir de 1.20 m podrán ingresar solos.','00:02:00',2014,0,NULL,20,2,200)
    , (3,3,3,9,'Batman Baticopteros','Únete al equipo de contra el crimen de Batman y toma un Baticoptero para ayudarlo a salvar la ciudad de los villanos.','Funcionando','0.90 m','00:01:00',2010,0,NULL,12,12,65)
    , (3,3,3,9,'DC Super Hero Girls','Disfruta la vista de la Zona Infantil a medida que tu góndola se mueve circularmente.','Funcionando','0.51 m acompañados de un adulto. A partir de 1.20 m podrán ingresar solos.','00:02:00',2023,0,NULL,15,4.5,30)
    , (1,3,3,15,'El Campo de Aventuras de Looney Tunes','Zona de juegos infantiles con laberintos, toboganes y escaleras donde pasaras horas de diversión y grandes aventuras como Los Looney Tunes.','Funcionando','90 cm','00:00:00',2009,0,NULL,NULL,0,0)
    , (6,3,3,9,'El Pingüino','Vive la divertida experiencia de girar al rededor del pingüino.','Funcionando','0.51m acompañados de un adulto. A partir de 1.05 m podrán ingresar solos.','00:01:00',2009,0,NULL,10,2,15)
    , (5,3,3,9,'El Tornado de Taz','Atrévete a probar este poderoso y divertido tornado provocado por el Taz donde no pararás de girar y gritar de emoción . ¡Así que prepárate para un emocionante viaje!','Funcionando','90 cm','00:02:00',2019,0,NULL,30,10,30)
    , (7,2,3,3,'Expresso Musical','Expreso Musical es un gran clásico de todos los tiempos que no te puedes perder. Este juego mecánico de gran velocidad y vueltas a desniveles en un solo sentido te harán vivir las más emocionantes sensaciones mientras la música correrá por tus venas. Todas las grandes épocas musicales y los más grandes éxitos del momento están reunidos aquí. Podrás cantar, gritar y también bailar si la velocidad del Expreso Musical te lo permite. ¿Te atreves?','Funcionando','1.20 m acompañados de un adulto. A partir de 1.40 m podrán ingresar solos.','00:01:00',1992,0,NULL,50,20,500)
    , (1,2,2,10,'Go Karts Teen Titans','Si la velocidad es lo tuyo… transfórmate  en un piloto y demuestra tu habilidad frente al volante en una explosiva carrera de Go Karts, compite contra tu familia o amigos en estos veloces autos en un desafiante circuito con curvas y rectas que te harán llegar al límite, has gritar a los espectadores al rebasar a tus contrincantes y llegar a la meta.','Funcionando','1.00 m','00:02:00',2015,0,NULL,60,0,700)
    , (1,1,1,15,'JUSTICE LEAGUE: Battle for Metropolis','Podrás ser parte del equipo de apoyo de la LIGA DE LA JUSTICIA, en un viaje completamente sensorial mientras pelean junto con BATMAN™, SUPERMAN™, LA MUJER MARAVILLA Y LINTERNA VERDE en contra de Lex Luthor, el Joker y sus secuaces. El recorrido es través de vehículos para seis pasajeros, en donde tendrán que ser más astutos que Lex Luthor y Joker para cumplir su misión: salvar Ciudad Metrópolis.','Funcionando','1.07 m acompañados de un adulto. A partir de 1.22 m podrán ingresar solos.','00:05:00',2016,0,6,NULL,10,400)
    , (5,3,3,9,'La Escuela de Vuelo de Sam Bigotes','Volar siempre ha sido uno de los mayores sueños de los pequeños. Juego de aviones con ligeros movimientos ascendentes y descendentes de manera circular, despega en el aire en esta aventura de alto vuelo que permite a los pequeños pilotos volar sus propios aviones. ¡Abrochen sus cinturones!','Funcionando','0.90 m','00:01:00',2019,0,NULL,30,10,30)
    , (2,2,2,3,'La Fiesta de las Tazas','¿Ya es la hora del té?, ¡Bromeamos! En este juego parecerá que te encuentras en un mundo de gigantes en donde tú serás el ingrediente principal a la hora del Té. No olvides dar vueltas para endulzar tu experiencia. Nos gustaría saber qué tantos giros puedes aguantar.  La fiesta de las tazas es lo primero que verás a tu ingreso o salida del parque, así que ¡no hay excusas para no visitarlo!','Funcionando','0.90 m acompañados de un adulto. A partir de 1.20 m podrán ingresar solos.','00:02:00',1987,0,48,10,3,20)
    , (8,3,3,3,'La Mini Torre de Sylvestre','Atrévete a subir a la torre de Silvestre y disfruta de divertidas subidas y bajadas.','Funcionando','0.90 m acompañados de un adulto.','00:01:00',1995,0,NULL,10,5,20)
    , (4,2,2,11,'Le Grand Carrousell','Uno de los juegos clásicos en todo el mundo que ha perdurado a través de los años, brindando diversión a toda la familia. Durante los giros en el Carrousel, todas las personas dan la misma cantidad de vueltas, pero unos dan giros más grandes que otros. Quienes dan giros más amplios son los que se encuentran más cerca de las orillas. Quienes dan giros más cortos son quienes se encuentran más cerca del centro. Los caballitos suben y bajan, las góndolas decoradas al estilo francés, a su vez también giran. ¿En dónde te quieres subir tú?','Funcionando','0.51 m acompañados de un adulto. A partir de 1.05 m podrán ingresar solos.','00:02:00',1998,0,NULL,NULL,6,35)
    , (5,3,3,3,'Looney Tunes Circo Express','Los más pequeños podrán disfrutar de este recorrido sobre una mini vía de tren con vueltas ligeras y una grandiosa vista alrededor de las casas de sus personajes favoritos.','Funcionando','0.90 m acompañados de un adulto.','00:02:00',2004,0,NULL,15,10,250)
    , (5,3,3,9,'Los Globos de Elmer','Descubre nuevas aventuras y siente la adrenalina de volar en las alturas con Elmer. Es un juego infantil con movimientos circulares, subidas y bajadas suaves. ¿Estás listo para la aventura?','Funcionando','0.51 m acompañados de un adulto. A partir de 0.90 m podrán ingresar solos.','00:01:00',2002,0,NULL,10,5,50)
    , (3,2,2,9,'Los Super villanos de Gotham City','Inicia el vuelo con tu familia y amigos acompañado por los enemigos de Batman. Este juego de columpios elevados giratorios te pondrá frente a frente con los villanos más conocidos de Gotham City.','Funcionando','1.20 m','00:01:00',2019,0,NULL,30,10,30)
    , (1,3,3,3,'Marvin el Marciano: Aventura Espacial','Éste será tu primer viaje a Marte en compañía de tu familia. Lo único que querrás hacer será abrir tus ojos tanto como puedas e intentar mirar a tu alrededor. Este juego tiene movimiento circular y una elevación ligera que hará que te sientas en otro planeta.','Funcionando','0.90 m acompañados de un adulto. A partir de 1.20 m podrán ingresar solos.','00:02:00',2017,0,NULL,10,3,20)
    , (6,1,1,12,'Medusa Steel Coaster','En 2014, llegó Medusa Steel Coaster, una atracción con base de madera y vías de acero, dando un recorrido totalmente nuevo.En esta experiencia, tu caída será de 36m y te impulsará a una velocidad que no te imaginarás. Para su remodelación se utilizaron 150, 630 tornillos de diferentes mdidas para fijar más de 188 piezas. Durante más de un kilómetro gozarás del vértigo que causan los giros inesperados y los descensos con grandes aceleraciones, en esta roller coaster híbrida favorita de los amantes de la adrenalina. ¡No la mires a los ojos o te convertirás en acero!','Funcionando','1.30 m','00:02:30',2014,0,24,93,25,914)
    , (5,3,3,9,'Pato Lucas Blaster','Entra a unas enormes cubetas junto al Pato Lucas en esta atracción familiar con pistolas de agua y movimientos circulares suaves. Diviértete con tus amigos y familiares empapando a los que están a tu lado o fuera del juego. ¡Tú no te salvarás!','Funcionando','0.90 m acompañados de un adulto. A partir de 1.20 m podrán ingresar solos.','00:01:00',2018,0,NULL,20,5,50)
    , (2,2,2,3,'Río Salvaje','El Río Salvaje simula los rápidos de un río de verdad. Se le conoce como rápidos a las partes de un río donde la velocidad del agua es mayor. ¿Te quieres mojar? Aquí mismo lo experimentarás. Los rápidos del Río Salvaje provocan que el agua salpique… además de que no escaparás de pasar por debajo de una cascada. En pocas palabras ¡saldrás empapado!','Funcionando','0.90 m acompañados de un adulto. A partir de 1.20 m podrán ingresar solos.','00:03:00',1992,0,108,15,0,740)
    , (1,2,2,13,'Rock & Roll','En este juego te queremos transportar a la magia de los años 60’s en donde todo era baile y diversión. No importa si eres chico o grande, atrévete a manejar uno de nuestros carros clásicos y disfruta de sus movimientos ascendentes y descendentes, mientras que tu vehículo girará sobre su propio eje creando una emoción inusual. Si quieres revivir esta época, no podrás perderte del ambiente del Rock & Roll en la Villa Hollywood.','Remodelacion','1.20 m','00:02:00',2000,0,NULL,45,12,240)
    , (6,2,2,9,'Ruleta','Desafía esta experiencia y prueba tu suerte en este juego de movimiento circular con subidas y bajadas en doble sentido. Podrás subir con toda tu familia y amigos. Apuéstale a tu diversión girando en esta ruleta donde el único ganador ¡serás tú!','Funcionando','0.90 m acompañados de un adulto. A partir de 1.20 m podrán ingresar solos.','00:03:00',1992,0,NULL,10,6,18)
    , (7,1,1,3,'Sling Shot','En Sling Shot estarás dentro de una resortera gigante.  En la parte alta de tu recorrido, y mientras vayas descendiendo, dejarás de sentir tu propio peso. Será la misma sensación que sienten los astronautas ante la falta de gravedad. ¿Y qué crees? Cuando vayas ascendiendo la sensación de tu peso se duplicará, ¡también es una sensación que los astronautas experimentan! ¡A disfrutar!','Funcionando','1.15 m','00:00:30',2016,40,2,115,90,20)
    , (3,2,2,8,'Superman Krypton Coaster','Es la roller coaster favorita de todos los pequeños amantes de la adrenalina. En ella que recorrerás 207 metros de vías a una velocidad de 45 kilómetros por hora para entrenar y en un futuro estén listos para seguir desfrutando de la increíble montaña Superman El Ultimo Escape.','Funcionando','0.90 m acompañados de un adulto, a partir de 1.20 m podrán ingresar solos.','00:02:30',2016,0,NULL,76,25,486)
    , (3,2,3,9,'The Joker y Harley Quinn','Déjate llevar por el impulso de ida y vuelta del juego, y disfruta de una increíble experiencia con la inigualable manera de The Joker y Harley Quinn.','Funcionando','1.05 m acompañados de un adulto. A partir de 1.20 m podrán ingresar solos.','00:01:00',2023,0,NULL,50,15,100)
    , (9,1,1,3,'Triple Torre Kilahuea','Una de las atracciones favoritas de Six Flags México por años. La enorme triple torre te llevará a más de 60 metros de altura en cuestión de segundos. Al llegar al punto más alto, te detendrás un momento para recuperar tu respiración y observar una imponente vista de la Ciudad de México, antes de experimentar una vertiginosa caída libre.','Funcionando','A partir de 1.40 m podrán ingresar solos. (solo con ticket VIP)','00:02:00',1992,0,12,80,60,120)
    , (9,2,2,14,'Tsunami','Realiza un viaje en Jeep en donde te adentrarás en lo más profundo de nuestra selva Polinesia. Tu objetivo será esquivar los obstáculos con movimientos e inclinaciones rápidas que Tsunami te tiene preparado. Esta mini montaña servirá de entrenamiento para los futuros fans de montañas rusas para cuando finalmente quieran experimentar juegos como Medusa Steel Coaste. Pero por el momento, esta roller coaster es de aventura para toda la familia, así que ¡nadie debe perdérsela!','Funcionando','1.05 m acompañados de un adulto. A partir de 1.20 m podrán ingresar solos.','00:02:00',1992,0,30,60,20,250)
    , (1,1,1,3,'X-Flight','En X-Flight vas sostenido de un arnés junto con uno o dos amigos y a la vez agarrados de un cable de acero para realizar un vuelo en forma de péndulo. Una vez que un cable de acero te lleve a la altura de 57 metros, tu deberás jalar una correa para experimentar una caída libre a una velocidad aproximada de 112 km. ¡En este juego tendrás una vista espectacular por encima del parque! Es una experiencia única en la vida, reservado para la gente que le gusta las emociones extremas y con fuerte carga de adrenalina.','Funcionando','1.07 m podrán ingresar solos, peso máximo por grupo de 3 personas: 385 kg','00:01:30',2017,60,3,128,57,200)
    , (11,2,2,15,'Adventure River','Esta travesía comienza cuando subes a tu llanta inflable y recorres los 650 m de este gran río lento, déjate llevar por el impulso del agua, diviértete y relájate con tu familia o amigos en esta aventura.','Funcionando','Sin consideraciones',NULL,2017,0,NULL,NULL,NULL,650)
    , (11,1,1,15,'Anaconda','Los pasajeros bajan a toda velocidad por el tobogán cerrado en una serie de giros en espiral, serpenteando hacia adelante y hacia atrás en una serie de espirales. ','Funcionando','Altura mínima 1.20 mts.',NULL,2017,0,NULL,NULL,NULL,NULL)
    , (11,1,1,15,'Aqua Racers','Reúne a tus amigos y compitan en una carrera a gran velocidad en esta atracción de 6 carriles, impulsados por el agua a una inclinación de 35º aproximadamente, alcanzarás una velocidad extrema.','Funcionando','Altura mínima 1.20 mts.',NULL,2017,0,NULL,NULL,NULL,NULL)
    , (11,1,1,15,'Big Surf','Surfea a una velocidad extrema y refréscate en esta aventura acuática, donde los amantes de la adrenalina se subirán una y otra vez.','Funcionando','Altura mínima 1.20 mts.',NULL,2017,0,NULL,NULL,NULL,NULL)
    , (11,1,1,15,'Cawabunga','Grita «Cawabunga» en este increíble tobogán cubierto, domina tus sentidos y deslízate hacia la adrenalina. ','Funcionando','Altura mínima 1.20 mts.',NULL,2017,0,NULL,NULL,NULL,NULL)
    , (11,3,2,15,'Coconut Bay','Los pequeños encontrarán diversión a lo grande en esta zona acuática diseñada especialmente para ellos completamente equipada para dominar las aguas de Hurricane Harbor Oaxtepec.','Funcionando','Altura mínima 90 cm',NULL,2017,0,NULL,NULL,NULL,NULL)
    , (11,3,3,15,'Family Snow Camp','¡Diviértete en esta fiesta de espuma! Entra en familia y diviértete con tus pequeños y pequeñas en esta atracción en la que podrás jugar con la espuma que simula nieve.','Funcionando','Sin consideraciones',NULL,2017,0,NULL,NULL,NULL,NULL)
    , (11,2,2,15,'Hurricane Bay','Esta impresionante alberca produce aire para generar grandes olas artificiales, sumérgete en la diversión.','Funcionando','Sin consideraciones',NULL,2017,0,NULL,NULL,NULL,NULL)
    , (11,1,3,15,'King Cobra','Asómbrate con su recorrido en forma circular con giros, vueltas y sorpresas emocionantes a través de extremas secciones cerradas y abiertas del enorme tobogán hasta llegar a una gran caída. Alcanza una velocidad de hasta 51 km/h Una caída repentina de 8 metros de altura en un ángulo de 50 grados; Un recorrido de más de 140 metros y Un final inesperado cuando los intrépidos que la desafiaron parecen ser tragados por las enormes mandíbulas de la cobra. Por seguridad, para ingresar a la atracción, el peso máximo permitido por persona es de 100 kg.','Funcionando','Altura mínima 1.20 mts.',NULL,2017,0,NULL,51,8,140)
    , (11,3,3,15,'Mini Racer','El entrenamiento perfecto de las y los más pequeños. Deja que se aventuren en estas divertidas mini resbaladillas que terminarán en un emocionante chapuzón.','Funcionando','Sin consideraciones',NULL,2017,0,NULL,NULL,NULL,NULL)
    , (11,1,1,15,'Shark Attack','No te arrepentirás de probar la sensación de este imponente tobogán en compañía de todos tus amigos, atrévete y disfruta de este gigantesto recorrido, que te llevará a sentir lo que es estar cerca de las mandíbulas de un gran tiburón.','Funcionando','Altura mínima 1.20 mts.',NULL,2017,0,NULL,NULL,NULL,NULL)
    , (11,2,2,15,'Splash Island','Toda la familia podrá disfrutar de las bondades de esta impresionante isla, ¡diviértete en familia!','Funcionando','Altura mínima 90 cm',NULL,2017,0,NULL,NULL,NULL,NULL)
    , (11,1,1,15,'Tornado','Experimenta este increíble recorrido que te pondrá en medio de un tornado de diversión. Capacidad: 2 o 4 Personas, Peso máximo combinado por balsa: 320kg.','Funcionando','Altura mínima 1.20 mts.',NULL,2017,0,4,NULL,NULL,NULL)
    , (11,1,1,15,'Twister','Estos toboganes gemelos se encargarán de acelerar tus emociones, lánzate en este recorrido con un amigo y compite para ver quien saldrá primero de esta gran aventura. Alcanza una velocidad acelerada en estos toboganes y aquatubos combinados con cortinas de agua a una inclinación de 14º aproximadamente.','Funcionando','Altura mínima 1.20 mts.',NULL,2017,0,NULL,NULL,NULL,NULL)
    , (11,1,1,15,'Typhoon','Inicia tu recorrido en la zona de lanzamiento, impúlsate a una inclinación de 14º aproximadamente y gira descontroladamente en un oasis de adrenalina.','Funcionando','Altura mínima 1.20 mts.',NULL,2017,0,NULL,NULL,NULL,NULL)
    , (11,1,1,15,'Volcano Blaster','Explota de adrenalina en esta aventura cayendo a grandes velocidades desde una altura de 10 mts. ','Funcionando','Altura mínima 1.20 mts.',NULL,2017,0,NULL,NULL,10,NULL)
;
