INSERT INTO restaurante(restaurante_id,categoria_restaurante_id, villa_id, nombre, descripcion)
VALUES ('1','6','2','Antigua Hacienda', 'Platillos tradicionales de la comida mexicana, tortillas hechas a mano, deliciosas bebidas, postres y un exquisito sazón.')
       , ('2','2','4','Café D París', 'Bebidas calientes o frías, crepas dulces o saladas, pastelería y delicioso pan')
       , ('3','5','7','Capones', '¡Deliciosa pizza y pasta!')
       , ('4','5','1','Centro de relleno boulevard Justice League', 'No hagas filas! Rellena tu vaso souvenir o cubeta palomera.')
       , ('5','3','1', 'DC VIllains Grill', 'Deliciosas hamburguesas, crujientes tiras de pollo y refrescantes malteadas.')
       , ('6','1','4','Estación Coca Cola Francés ', 'Bebidas de la familia Coca Cola, Agua Ciel, Palomitas, Nachos, Icee y mucho más.')
       , ('7','1','1', 'Estación Coca Cola Hollywood', 'Bebidas de la familia Coca Cola, Agua Ciel, Palomitas, Nachos, Icee y mucho más.')
       , ('8','1','2','Estación Fanta', 'Bebidas de la familia Coca Cola, Agua Ciel, Palomitas, Nachos, Icee y mucho más.')
       , ('9','7','2', 'Funnel Cake ', 'Funnel Cake, bebidas, churros rellenos y más')
       , ('10','4','2', 'Go Fresh Mexicano', 'Variedad de frutas de temporada, agua de sabor y más.')
       , ('11','4','2','Go Fresh Suizo', 'Variedad de frutas de temporada, agua de sabor y más.')
       , ('12','3','1','Grill Hollywood', '¡Deliciosos Hot Dogs a la parrilla!')
       , ('13','3','1', 'Hot Dog Grill Boulevard Justice League', 'Los mejores hot dogs de Metropolis: texas chilli dog, pulled pork y tocino.')
       , ('14','3','1', 'Johnny Rockets Hollywood', 'Hamburguesas, papas fritas, aros de cebolla y malteadas.')
       , ('15','3','2', 'Johnny Rockets Mexicano', 'Hamburguesas, papas fritas, aros de cebolla y malteadas.')
       , ('16','1','1','La Barrica Hollywood', 'Refrescante cerveza Corona.')
       , ('17','2','10', 'La Crepería', 'Bebidas calientes o frías, crepas dulces o saladas.')
       , ('18','3','2','Papa Kahuna', 'Papas al horno rellenas de jamón, tocino, o champicrema, nachos, icee y más.')
       , ('19','3','6', 'Parrilla Vaquera', 'Hamburguesas, papas fritas, y ensalada de vegetales.')
       , ('20','3','6', 'Saloon Corona', 'Comida del viejo Oeste: Cortes de carne, alitas, ensaladas, postres y más.')
       , ('21','5','1','Six Pizza Hollywood', 'Variedad de pizzas, elige tu favorita.')
       , ('22','5','6', 'Six Pizza Vaquero', 'Variedad de pizzas, elige tu favorita.')
       , ('23','1','5', 'Super Snacks', 'Bebidas de la familia Coca Cola, Agua Ciel, Palomitas, Nachos, Icee y mucho más.')
       , ('24','3','2', 'Super Villanos Grill', 'Hamburguesas, papas fritas, y ensalada de vegetales.')
       , ('25','6','2','Taquería Jacaranda', 'Tacos al pastor, de suadero, bistec, gringas y más.')
       , ('26','3','9','Volcano Wings', 'Deliciosas alitas, boneless y refrescante cerveza de barril.')
       , ('27','1','11', 'Beachside Grill', 'Disfruta con el calor de una cerveza sola o preparada tu elijes! También prueba nuestros nuevos calimochos o si quieres algo más tropical te va a encantar nuestra piña colada! También para los peques se refresquen pídeles una canica seguro les encantará!')
       , ('28','6','11', 'Fábrica de Pollo', 'Prueba nuestros tradicionales pollos rostizados acompañados de una ensalada')
       , ('29','1','11', 'H2O Snacks', 'Rellena tu cubeta palomera o vaso souvenir')
       , ('30','3','11','Johnny Rockets', 'Hamburguesas, papas fritas, aros de cebolla y malteadas.')
       , ('31','6','11','La Antigua Hacienda', 'Aquí encontrarás una gran variedad de gastronomía mexicana')
       , ('32','1','11','La Hamaca Snacks', 'Rellena tu cubeta palomera o tu vaso souvenir')
       , ('33','1','11', 'Sharks Snacks', 'Refréscate con una botella de agua o un refresco o alguno de los sabores de nuestras bebidas congeladas carbonatadas, ¿antojo de una papas? Aquí podrás encontrarlas para compartirlas')
       , ('34','5','11','Six Pizza', 'Aquí podrás encontrar tu pizza favorita seguramente pepperoni, hawaiana disfrútalas al máximo. Complementa tu experiencia con una pasta a la boloñesa. No, olvides que también contamos con ensaladas para acompañar tus alimentos.');
       
