INSERT INTO restaurante(restaurante_id, nombre, descripcion, categoria_restaurante_id, villa_id)
VALUES ('1', 'Antigua Hacienda', 'Platillos tradicionales de la comida mexicana, tortillas hechas a mano, deliciosas bebidas, postres y un exquisito sazón.','6','2')
       , ('2', 'Café D´ París', 'Bebidas calientes o frías, crepas dulces o saladas, pastelería y delicioso pan','2','4')
       , ('3', 'Capone\'s  ', '¡Deliciosa pizza y pasta!','5','7')
       , ('4', 'Centro de relleno boulevard Justice League', 'No hagas filas! Rellena tu vaso souvenir o cubeta palomera.','5','1')
       , ('5', 'DC VIllains Grill', 'Deliciosas hamburguesas, crujientes tiras de pollo y refrescantes malteadas.','3','1')
       , ('6', 'Estación Coca Cola Francés ', 'Bebidas de la familia Coca Cola, Agua Ciel, Palomitas, Nachos, Icee y mucho más.','1','4')
       , ('7', 'Estación Coca Cola Hollywood', 'Bebidas de la familia Coca Cola, Agua Ciel, Palomitas, Nachos, Icee y mucho más.','1','1')
       , ('8', 'Estación Fanta', 'Bebidas de la familia Coca Cola, Agua Ciel, Palomitas, Nachos, Icee y mucho más.','1','2')
       , ('9', 'Funnel Cake  ', 'Funnel Cake, bebidas, churros rellenos y más','7','2')
       , ('10', 'Goo Fresh Mexicano', 'Variedad de frutas de temporada, agua de sabor y más.','4','2')
       , ('11', 'Goo Fresh Suizo', 'Variedad de frutas de temporada, agua de sabor y más.','4','2')
       , ('12', 'Grill Hollywood', '¡Deliciosos Hot Dogs a la parrilla!','3','1')
       , ('13', 'Hot Dog Grill Boulevard Justice League', 'Los mejores hot dogs de Metropolis: texas chilli dog, pulled pork y tocino.','3','1')
       , ('14', 'Johnny Rockets Hollywood', 'Hamburguesas, papas fritas, aros de cebolla y malteadas.','3','1')
       , ('15', 'Johnny Rockets Mexicano', 'Hamburguesas, papas fritas, aros de cebolla y malteadas.','3','2')
       , ('16', 'La Barrica Hollywood', 'Refrescante cerveza Corona.','1','1')
       , ('17', 'La Crepería', 'Bebidas calientes o frías, crepas dulces o saladas.','2','10')
       , ('18', 'Papa Kahuna', 'Papas al horno rellenas de jamón, tocino, o champicrema, nachos, icee y más.','3','2')
       , ('19', 'Parrilla Vaquera', 'Hamburguesas, papas fritas, y ensalada de vegetales.','3','6')
       , ('20', 'Saloon Corona', 'Pueblo Vaquero', 'Comida del viejo Oeste: Cortes de carne, alitas, ensaladas, postres y más.','3','6')
       , ('21', 'Six Pizza Hollywood', 'Variedad de pizzas, elige tu favorita.','5','1')
       , ('22', 'Six Pizza Vaquero', 'Variedad de pizzas, elige tu favorita.','5','6')
       , ('23', 'Super Snacks', 'Bebidas de la familia Coca Cola, Agua Ciel, Palomitas, Nachos, Icee y mucho más.','1','5')
       , ('24', 'Super Villanos Grill', 'Hamburguesas, papas fritas, y ensalada de vegetales.','3','2')
       , ('25', 'Taquería Jacaranda', 'Tacos al pastor, de suadero, bistec, gringas y más.','6','2')
       , ('26', 'Volcano Wings', 'Deliciosas alitas, boneless y refrescante cerveza de barril.','3','9')
       , ('27', 'Beachside Grill', 'Disfruta con el calor de una cerveza sola o preparada tu elijes! También prueba nuestros nuevos calimochos o si quieres algo más tropical te va a encantar nuestra piña colada! También para los peques se refresquen pídeles una canica seguro les encantará!','1','11')
       , ('28', 'Fábrica de Pollo', 'Prueba nuestros tradicionales pollos rostizados acompañados de una ensalada','6','11')
       , ('29', 'H2O Snacks', 'Rellena tu cubeta palomera o vaso souvenir','1','11')
       , ('30', 'Johnny Rockets', 'Hamburguesas, papas fritas, aros de cebolla y malteadas.','3','11')
       , ('31', 'La Antigua Hacienda', 'Aquí encontrarás una gran variedad de gastronomía mexicana','6','11')
       , ('32', 'La Hamaca Snacks', 'Rellena tu cubeta palomera o tu vaso souvenir', '1','11')
       , ('33', 'Sharks Snacks', 'Refréscate con una botella de agua o un refresco o alguno de los sabores de nuestras bebidas congeladas carbonatadas, ¿antojo de una papas? Aquí podrás encontrarlas para compartirlas', '1','11')
       , ('34', 'Six Pizza', 'Aquí podrás encontrar tu pizza favorita seguramente pepperoni, hawaiana disfrútalas al máximo. Complementa tu experiencia con una pasta a la boloñesa. No, olvides que también contamos con ensaladas para acompañar tus alimentos.', '5','11');
       
