INSERT INTO servicio (servicio_id
                            ,parque_id
                            , nombre
                            , descripcion
                            , precio
                            , deposito_inicial
) VALUES
    (1,1,'ATM','¿Necesitas dinero en efectivo? ¡No es ningún problema! \n Nuestros Cajeros Automáticos están convenientemente ubicados por todo el parque',0,0)
    , (2,1,'CARRIOLAS','¿Necesitas un descanso por cargar a tus niños mucho tiempo en el parque? Las carriolas se rentan por orden de llegada. Para tu conveniencia, rentamos carriolas sencillas y dobles en el Pueblo Mexicano.',120,120)
    , (3,1,'CENTRO PARA EL CUIDADO DE BEBÉS','Disponemos de un centro para que las mamás puedan atender a sus bebés lactantes y cambiar los pañales. Éste se encuentra dentro del Centro de Información, en el Pueblo Suizo. También, en todos los sanitarios de damas y en los de caballeros, encontrarás espacio para cambiar a tu bebé.',0,0)
    , (4,1,'CUBETA PALOMERA Y VASO REFIL','Los productos de cubeta palomera y vaso refill, deberán ser del año presente. Es decir, del año calendario que se está cursando, siempre y cuando sea el producto que Six Flags México o Hurricane Harbor Oaxtepec hayan autorizado. Cubetas y Vasos de años anteriores no podrán ingresar al parque.',50,400)
    , (5,1,'CUIDADO DE MASCOTAS','Sabemos que amas a tus mascotas y nosotros también amamos a los animales, pero no pueden venir a Six Flags México contigo. El servicio de Cuidador de Mascotas no está disponible. Las mascotas no pueden dejarse, ni atarse a un vehículo desatendido en el estacionamiento.',0,0)
    , (6,1,'ESTACIONAMIENTO AUTO PRIMERA HORA','Recuerda que el parque y nuestro estacionamiento tienen un aforo máximo. Por tal motivo, en caso de ser necesario el parque cerrará sus puertas por cuestiones de seguridad (aplica para socios pase anual y/o boletos comprados en línea)',30,0)
    , (7,1,'ESTACIONAMIENTO AUTO TODO EL DÍA','Tarifa de todo el día pagando antes de las 14:00 horas.',200,0)
    , (8,1,'ESTACIONAMIENTO AUTO BOLETO EXTRAVIADO','En caso de perder el boleto, el parque podría cobrar una tarifa para reemitir un boleto de estacionamiento. Asegúrate de preguntar sobre cualquier tarifa asociada y estar preparado para cubrirla si es necesario.',250,0)
    , (9,1,'ESTACIONAMIENTO AUTOBUS PRIMERA HORA','Recuerda que el parque y nuestro estacionamiento tienen un aforo máximo. Por tal motivo, en caso de ser necesario el parque cerrará sus puertas por cuestiones de seguridad (aplica para socios pase anual y/o boletos comprados en línea)',40,0)
    , (10,1,'ESTACIONAMIENTO AUTOBUS TODO EL DÍA','Tarifa de todo el día pagando antes de las 14:00 horas.',210,0)
    , (11,1,'ESTACIONAMIENTO AUTOBUS BOLETO EXTRAVIADO','En caso de perder el boleto, el parque podría cobrar una tarifa para reemitir un boleto de estacionamiento. Asegúrate de preguntar sobre cualquier tarifa asociada y estar preparado para cubrirla si es necesario.',250,0)
    , (12,1,'PRIMEROS AUXILIOS','Estación de Primeros Auxilios. Está al lado de Huracán, en Pueblo Vaquero.',0,0)
    , (13,1,'LOCKERS PEQUEÑO','Para tu comodidad el parque cuenta con el servicio de renta de lockers, ubicados en : * Entrada del Parque * Medusa * The Dark Knight Coaster * Go Karts * The Joker * Superman * Justice League Battle.\n “El número de lockers es limitado.” Te recomendamos una cangurera simple para disfrutar de los Juegos Mecánicos.',150,150)
    , (14,1,'LOCKERS MEDIANO','Para tu comodidad el parque cuenta con el servicio de renta de lockers, ubicados en : * Entrada del Parque * Medusa * The Dark Knight Coaster * Go Karts * The Joker * Superman * Justice League Battle.\n “El número de lockers es limitado.” Te recomendamos una cangurera simple para disfrutar de los Juegos Mecánicos.',200,200)
    , (15,1,'LOCKERS GRANDE','Para tu comodidad el parque cuenta con el servicio de renta de lockers, ubicados en : * Entrada del Parque * Medusa * The Dark Knight Coaster * Go Karts * The Joker * Superman * Justice League Battle.\n “El número de lockers es limitado.” Te recomendamos una cangurera simple para disfrutar de los Juegos Mecánicos.',250,250)
    , (16,1,'SILLAS DE RUEDAS Y ASISTENCIA PARA VISITANTES CON DISCAPACIDAD','Nos esforzamos para garantizar que Six Flags México sea divertido y accesible para todos. Muchos de nuestros visitantes con discapacidad disfrutan en el parque todos los días. Podrás ingresar con sillas de ruedas y carros eléctricos. Son bienvenidos los visitantes con discapacidad y queremos hacer que su visita sea confortable e inolvidable. Los visitantes con discapacidad que requieran la ayuda de un Asistente de Cuidado Personal (ACP) con el fin de disfrutar la igualdad de acceso al parque, pueden solicitar a Six Flags México un pase sin costo para su ACP. Después de comprar sus boletos, por favor dirígete a Atención al Visitante y pregunta a los miembros del equipo por una solicitud de acceso para Asistente de Cuidado Personal. Este acceso NO es para disfrutar del parque, sino para realizar los cuidados que la persona con discapacidad requiera.',600,150)
    , (17,1,'VIP NANNY','Enfocado a padres y madres de familia que deseen que sus hijos e hijas tengan una segura y educativa diversión dentro del parque sin que ellos estén presentes.',4000,4000)
    , (18,2,'ATM','¿Necesitas dinero en efectivo? ¡No es ningún problema! \n Nuestros Cajeros Automáticos están convenientemente ubicados por todo el parque',0,0)
    , (19,2,'CAMBIADORES PARA BEBÉS','Disponemos de un centro para que las mamás puedan atender a sus bebés lactantes y cambiar los pañales. Éste se encuentra dentro del Centro de Información, en el Pueblo Suizo. También, en todos los sanitarios de damas y en los de caballeros, encontrarás espacio para cambiar a tu bebé.',0,0)
    , (20,2,'PRIMEROS AUXILIOS','Estación de Primeros Auxilios. Está al lado de Huracán, en Pueblo Vaquero.',0,0)
    , (21,2,'CARRIOLAS','¿Necesitas un descanso por cargar a tus niños mucho tiempo en el parque? Las carriolas se rentan por orden de llegada. Para tu conveniencia, rentamos carriolas sencillas y dobles en el Pueblo Mexicano.',120,120)
    , (22,2,'SILLAS DE RUEDAS Y ASISTENCIA PARA VISITANTES CON DISCAPACIDAD','Nos esforzamos para garantizar que Six Flags México sea divertido y accesible para todos. Muchos de nuestros visitantes con discapacidad disfrutan en el parque todos los días. Podrás ingresar con sillas de ruedas y carros eléctricos. Son bienvenidos los visitantes con discapacidad y queremos hacer que su visita sea confortable e inolvidable. Los visitantes con discapacidad que requieran la ayuda de un Asistente de Cuidado Personal (ACP) con el fin de disfrutar la igualdad de acceso al parque, pueden solicitar a Hurricane Harbor Oaxtepec un pase sin costo para su ACP. Después de comprar sus boletos, por favor dirígete a Atención al Visitante y pregunta a los miembros del equipo por una solicitud de acceso para Asistente de Cuidado Personal. Este acceso NO es para disfrutar del parque, sino para realizar los cuidados que la persona con discapacidad requiera.',600,150)
    , (23,2,'CUBETA PALOMERA Y VASO REFIL','Los productos de cubeta palomera y vaso refill, deberán ser del año presente. Es decir, del año calendario que se está cursando, siempre y cuando sea el producto que Six Flags México o Hurricane Harbor Oaxtepec hayan autorizado. Cubetas y Vasos de años anteriores no podrán ingresar al parque.',50,400)
    , (24,2,'LOCKERS PEQUEÑO','Para tu comodidad el parque cuenta con el servicio de renta de lockers, ubicados en : * Frente a zona de Island Traders * A un costado de la atracción Tornado * Atrás de la tienda de souvenirs Cyclone',150,150)
    , (25,2,'LOCKERS MEDIANO','Para tu comodidad el parque cuenta con el servicio de renta de lockers, ubicados en : * Frente a zona de Island Traders * A un costado de la atracción Tornado * Atrás de la tienda de souvenirs Cyclone',200,200)
    , (26,2,'LOCKERS GRANDE','Para tu comodidad el parque cuenta con el servicio de renta de lockers, ubicados en : * Frente a zona de Island Traders * A un costado de la atracción Tornado * Atrás de la tienda de souvenirs Cyclone',250,250)
    , (27,2,'CUIDADO DE MASCOTAS','Sabemos que amas a tus mascotas y nosotros también amamos a los animales, pero no pueden venir a Six Flags México contigo. El servicio de Cuidador de Mascotas no está disponible. Las mascotas no pueden dejarse, ni atarse a un vehículo desatendido en el estacionamiento.',0,0)
;