INSERT INTO beneficio(
    descripcion
)
VALUES
     ('Acceso de un día a Six Flags México')
     ,('Acceso de un día a Hurricane Harbor Oaxtepec')
     ,('Visitas ilimitadas a todos los parques Six Flags y Hurricane Harbor.')
     ,('Estacionamiento general sin costo.')
     ,('15% de descuento en Alimentos y Souvenirs seleccionados.')
     ,('Vigencia al 31 de diciembre de 2024.')
     ,('1 Flash Pass de un acceso (en total durante la vigencia del Pase.)')
     ,('2 boletos a precio especial de $749.00 c/u para Six Flags México (aplicable a partir de la segunda visita).')
     ,('2 boletos a precio especial de $252.00 c/u para Hurricane Harbor Oaxtepec.')
     ,('Estacionamiento sin costo en Zona Diamond (sujeto a capacidad).')
     ,('20% de descuento en Alimentos y Souvenirs seleccionados.')
     ,('4 Flash Pass de un acceso (en total durante la vigencia del Pase).')
     ,('5 boletos a precio especial de $749.00 c/u para Six Flags México (aplicable a partir de la segunda visita).')
     ,('5 boletos a precio especial de $252.00 c/u para Hurricane Harbor Oaxtepec.')
     ,('Vaso Souvenir con refill ilimitado de refresco (periodo de 20 minutos entre cada refill).')
     ,('50% de descuento entre semana en Cabana Regular en Hurricane Harbor.')
     ,('¡Agrega un Plan de Alimentos a tu Pase 2024!')
     ,('Disfruta de una o dos comidas en cada visita (3 horas entre cada redención).')
     ,('Úsalo en cualquier parque al que tenga acceso tu Pase 2024.')
     ,('Viaje Redondo en autobús de calidad turística')
     ,('Acceso de un día al parque acuático')
     ,('¡Disfruta una comida en cada visita durante la vigencia de tu Pase!')
     ,('¡Disfruta dos comidas en cada visita durante la vigencia de tu Pase! Con un intervalo de 3 horas entre cada redención.')
     ,('¡Obtén una comida, un snack y un refresco mediano o agua embotellada 600ml!')
     ,('Descuento en 10 boletos para amigos en Six Flags México')
     ,('Descuento en 10 boletos para amigos en Hurricane Harbor Oaxtepec')
     ,('Descuento en 5 boletos para amigos en Six Flags México')
     ,('Descuento en 5 boletos para amigos en Hurricane Harbor Oaxtepec')
     ,('10% de descuento en Alimentos y Souvenirs seleccionados.')
     ,('Descuento en 2 boletos para amigos en Six Flags México')
     ,('¡Aprovecha tu visita al máximo! Adquiere tu Flash Pass e ingresa a tus montañas rusas favoritas por fila rápida')
     ,('Paga tu estacionamiento antes de llegar al parque y ahorra tiempo y dinero.')
     ,('Visitas ilimitadas a Hurricane Harbor Oaxtepec.')
     ,('5% de descuento en Alimentos y Souvenirs seleccionados.')
     ,('Vigencia al 8 de septiembre de 2024.')
     ,('Disfruta con tu familia y amigos en una Cabana privada.')
     ,('No te estreses buscando un lugar con sombra durante tu visita. ¡Reserva tus sillas!')
     ,('Asegura un lugar privado para descansar con tu acompañante. ¡Reserva un bimini anticipadamente!')
     ,('Disfruta de un lugar privado al frente de nuestras principales atracciones. ¡Reserva tu Tent!')
     ,('Al rentar nuestra zona Food Garden, puedes traer tus propios alimentos en una hielera de máximo 63.5 cm. x 35.5 cm. x 35.5 cm. (48 cuartos). No se permite vidrio de ningún tipo.')
     ,('Con el Plan de Alimentos de un Día, disfruta de una comida, un snack y un refresco mediano por un solo pago. ¡La mejor forma de alimentarte mientras visitas Six Flags! ')
     ,('Admisión VIP al parque para el día seleccionado.')
     ,('Acceso ilimitado con Flash Pass a los toboganes.')
     ,('Una comida a elegir y un refresco mediano.')
     ,('Tour con un guía privado durante la visita (por 8 horas)')
     ,('Admisión VIP al parque el día de la visita.')
     ,('Estacionamiento Preferente sin costo adicional.')
     ,('Acceso por fila rápida a los toboganes.*')
     ,('Acceso por fila preferente a los juegos mecánicos.*')
     ,('Una comida y un snack.')
     ,('Un snack')
     ,('Una comida o cena (menú VIP del día).')
     ,('Bebidas ilimitadas (no alcohólicas).')
     ,('Una playera souvenir.')
     ,('Uso de una llanta para Adventure River.')
     ,('Un acceso a una atracción a elegir entre X-Flight, Sling Shot, Go Karts o Ghost Face.')
     ,('Acceso a la nueva VIP Lounge, ubicada en Pueblo Francés.**')
     ,('Admisión VIP Al parque el día seleccionado.')
     ,('Acceso ilimitado por fila preferente a los juegos mecánicos.')
     ,('Dos accesos a la rampa de nieve.')
     ,('Una cena VIP (se asignará un horario el día de la visita).')
     ,('Acceso a la nueva VIP Lounge.*')
     ,('Admisión VIP Al parque el día seleccionado (sólo para niñas y niños entre 90 cm y 1.20 m de estatura).')
     ,('Vigencia al 31 de diciembre de 2022.')
     ,('Vigencia al 31 de diciembre de 2023.')
     ,('Visitas en fechas específicas a Six Flags México, Hurricane Harbor Oaxtepec y parques de Six Flags región Sur')
     ,('Estacionamiento sin costo en Hurricane Harbor Oaxtepec y de lunes a viernes en Six Flags México')
     ,('Dos cupones de descuento en boletos de un día para amigos y familiares.')
     ,('Un Flash Pass de un acceso para juegos mecánicos participantes')
     ,('Durante la vigencia de tu plan anual podrás disfrutar de visitas ilimitadas a todos los parques temáticos de Six Flags y Hurricane Harbor Oaxtepec.')
     ,('Días de estacionamiento sin costo en Hurricane Harbor Oaxtepec y Six Flags México.')
     ,('Incluye dos Junior Pass para menores de 1.07 m.')
     ,('15% de Descuento en Souvenirs')
     ,('15% de Descuento en Alimentos')
     ,('5 Flash Pass de un acceso para juegos mecánicos participantes')
     ,('5 descuentos en boletos de un día para amigos y familiares. ')
     ,('Acceso a Estacionamiento Preferente')
     ,('20% de Descuento en Souvenirs y Aliment')
     ,('10 Descuentos en boletos de un día para amigos y familiares al año')
     ,('Un descuento del 50% en Flash Pass Platino')
     ,('10 Flash Pass de un acceso')
     ,('Incluye diversión ilimitada en nuestros juegos mecánicos y shows, con excepción de eventos especiales y ciertas atracciones con costo adicional.')
     ,('¡THE FLASH Pass Junior reduce el tiempo de espera hasta en un 90 % para tus atracciones favoritas para niños y familias! Se requiere entrada al parque (se vende por separado).')
     ,('Al rentar nuestra zona Food Garden, puedes traer tus propios alimentos en una hielera de máximo 63.5 cm. x 35.5 cm. x 35.5 cm. (48 cuartos).')
     ,('Pasar la noche dentro del parque, y despertar para disfrutar de toboganes, atracciones acuáticas y todo lo que el Oasis Tropical tiene para ofrecerte.')
;